### ISSUE TITLE
Configure close pull request - Restrict Mode

### ISSUE THREAD

**Issue by giansalex** [giansalex/branching-workflow#2]
Parameter in config:

```yaml
restrict:
  - target: master
    source: ppr
    close: true
```
